# .github/workflows/tests.yml
name: Tests & Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        # This working directory is correct
        working-directory: ./proj2/stackshack 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        # FIX 1: Add PYTHONPATH=. to fix imports for the 'tests/' directory
        # FIX 2: Add the 'tests/' directory to the pytest command
        PYTHONPATH=. pytest menuManagementTests/ tests/ \
          --cov=models \
          --cov=controllers \
          --cov=routes \
          --cov-report=xml \
          --cov-report=term

    - name: Upload coverage report to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./proj2/stackshack/coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./proj2/stackshack/coverage.xml
        fail_ci_if_error: false