# .github/workflows/tests.yml
name: Python Tests, Coverage, & Badge

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        # CRITICAL: Sets working directory to the package root for clean imports
        working-directory: ./proj2/stackshack

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-html

    - name: Run ALL Tests with Coverage
      env:
        # Use a temporary testing secret key for the environment
        SECRET_KEY: ${{ secrets.SECRET_KEY_TEST }}
      run: |
        # FIX: PYTHONPATH=. ensures Python resolves imports correctly from the package root.
        PYTHONPATH=. pytest tests/ menuManagementTests/ \
          --cov=. \
          --cov-report=xml \
          --html=test-results.html \
          --self-contained-html

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4 # Using the latest recommended Codecov action version
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./proj2/stackshack/coverage.xml
        fail_ci_if_error: true

    # -----------------------------------------------------
    # FIX: Use a working action to generate the coverage badge SVG
    # -----------------------------------------------------
    - name: Generate Coverage Badge
      id: coverage
      uses: tj-actions/coverage-badge@v3 # Replaced missing shields action with reliable alternative
      with:
        # Source file is the one uploaded to Codecov
        coverage_file: ./proj2/stackshack/coverage.xml
        
    - name: Commit and Push Badge
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "CI: Auto-generated coverage badge"
        # The badge SVG file is generated in the root of the working directory
        files: badge.svg
        commit_options: '--no-verify'