# .github/workflows/tests.yml
name: Python Tests, Coverage, & Codecov Upload

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        # CRITICAL: Sets working directory to the package root for correct file access
        working-directory: ./proj2/stackshack

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install testing dependencies
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-html

    - name: Run ALL Tests and Generate Coverage Report
      env:
        # Set dummy key for environment consistency
        SECRET_KEY: 'ci-testing-key-12345'
      run: |
        # FIX: PYTHONPATH=. resolves the ImportError by telling Python to treat 
        # the current directory (stackshack/) as the package root.
        PYTHONPATH=. pytest tests/ menuManagementTests/ \
          --cov=. \
          --cov-report=xml \
          --html=test-results.html \
          --self-contained-html

    - name: Upload coverage report to Codecov
      # This step handles the badge data upload automatically.
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./proj2/stackshack/coverage.xml
        fail_ci_if_error: true