name: Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./proj2/stackshack

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        pytest menuManagementTests/ \
          --cov=models.menu_item \
          --cov=controllers.menu_controller \
          --cov=routes.menu_routes \
          --cov-report=xml \
          --cov-report=term

    - name: Upload coverage report to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./proj2/stackshack/coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./proj2/stackshack/coverage.xml
        fail_ci_if_error: false